/**
 * remediation-pr/dependency-fix.ts — mechanical fix for a pinned dependency
 * with a known-good fixed version (from ThreatAdvisory.patchedVersion via
 * packages/core/src/pentest/threat-intel).
 *
 * Scope, intentionally narrow: bumps ONE version string in ONE manifest
 * field it can locate unambiguously (dependencies/devDependencies/
 * peerDependencies in package.json). Refuses if the package isn't found,
 * is version-ranged in a way we can't safely rewrite (e.g. already a range
 * spanning the fix), or the manifest isn't valid JSON.
 *
 * © OTT Cybersecurity LLC — https://lyrie.ai
 */

import type { DependencyFixFinding, GeneratedDiff, MechanicalFixResult, MechanicalFixSkipped } from "./types";

const DEP_FIELDS = ["dependencies", "devDependencies", "peerDependencies", "optionalDependencies"] as const;

/** Strip a leading semver range operator (^, ~, >=, etc.) so version strings compare cleanly. */
function stripRangeOperator(v: string): string {
  return v.replace(/^[\^~>=<]+/, "").trim();
}

export function generateDependencyFix(
  finding: DependencyFixFinding,
  manifestContent: string,
): MechanicalFixResult | MechanicalFixSkipped {
  let manifest: Record<string, unknown>;
  try {
    manifest = JSON.parse(manifestContent);
  } catch (err) {
    return { ok: false, reason: `${finding.manifestFile} is not valid JSON: ${err}` };
  }

  let fieldFound: (typeof DEP_FIELDS)[number] | undefined;
  let pinnedValue: string | undefined;

  for (const field of DEP_FIELDS) {
    const deps = manifest[field] as Record<string, string> | undefined;
    if (deps && typeof deps[finding.packageName] === "string") {
      fieldFound = field;
      pinnedValue = deps[finding.packageName];
      break;
    }
  }

  if (!fieldFound || pinnedValue === undefined) {
    return {
      ok: false,
      reason: `"${finding.packageName}" not found in any dependency field of ${finding.manifestFile}`,
    };
  }

  const currentBare = stripRangeOperator(pinnedValue);
  if (currentBare !== finding.currentVersion) {
    // The manifest doesn't match what the finding claims is currently
    // pinned (e.g. someone already bumped it, or a workspace range is in
    // play) \u2014 refuse rather than risk clobbering an unrelated version.
    return {
      ok: false,
      reason:
        `manifest has "${finding.packageName}": "${pinnedValue}" but the finding expected current version ` +
        `"${finding.currentVersion}" \u2014 refusing to guess; needs a human to confirm the right value.`,
    };
  }

  // Preserve whatever range operator prefix was already there (^, ~, exact).
  const operatorMatch = pinnedValue.match(/^[\^~>=<]+/);
  const operator = operatorMatch ? operatorMatch[0] : "";
  const newPinned = `${operator}${finding.fixedVersion}`;

  const before = manifestContent;
  // Textual replace (not JSON.stringify round-trip) to preserve formatting/
  // key ordering/comments exactly, matching how a human would edit it.
  const needle = `"${finding.packageName}": "${pinnedValue}"`;
  if (!before.includes(needle)) {
    return {
      ok: false,
      reason: `could not locate exact text ${JSON.stringify(needle)} in ${finding.manifestFile} for a safe textual replace`,
    };
  }
  const replacement = `"${finding.packageName}": "${newPinned}"`;
  const after = before.replace(needle, replacement);

  const branchName = `lyrie-auto-fix/bump-${finding.packageName.replace(/[^a-z0-9-]/gi, "-")}-${finding.fixedVersion}`;
  const prTitle = `fix(deps): bump ${finding.packageName} to ${finding.fixedVersion}${finding.cve ? ` (${finding.cve})` : ""}`;
  const prBody = [
    "## Lyrie auto-remediation \u2014 mechanical fix",
    "",
    finding.cve
      ? `Lyrie's threat-intel feed cross-referenced \`${finding.packageName}@${finding.currentVersion}\` against \`${finding.cve}\`, which has a known fixed version.`
      : `\`${finding.packageName}@${finding.currentVersion}\` has a known fixed version available.`,
    "",
    `**Fix:** bump \`${finding.packageName}\` from \`${pinnedValue}\` to \`${newPinned}\` in \`${finding.manifestFile}\` (${fieldFound}).`,
    "",
    "This is a mechanical, single-line version-string change (confidence: high). Please run your test suite " +
      "before merging \u2014 this PR does not verify the new version is behaviourally compatible, only that a fix " +
      "version exists.",
    "",
    "\u2014 generated by Lyrie's auto-remediation PR generator (packages/core/src/remediation-pr/)",
  ].join("\n");

  return {
    ok: true,
    diff: {
      file: finding.manifestFile,
      newContent: after,
      before,
      after,
      prTitle,
      prBody,
      branchName,
    } satisfies GeneratedDiff,
  };
}
