/**
 * remediation-pr/header-fix.ts — mechanical fix for a missing security
 * header on a Next.js app, via next.config.ts's `headers()` hook.
 *
 * Scope, intentionally narrow: this only ADDS a header entry. It never
 * rewrites unrelated config, never removes existing headers() rules, and
 * refuses (returns a skip reason) if it can't confidently locate/produce a
 * valid insertion point — see "Do NOT attempt to auto-fix arbitrary
 * application logic bugs" in the prompt contract for why this stays this
 * conservative.
 *
 * © OTT Cybersecurity LLC — https://lyrie.ai
 */

import type { GeneratedDiff, MechanicalFixResult, MechanicalFixSkipped, MissingHeaderFinding } from "./types";

const EMPTY_NEXT_CONFIG = `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // output: "standalone",
};

export default nextConfig;
`;

/**
 * Generate a next.config.ts diff that adds `finding.header` via the
 * `headers()` async function. `currentContent` is the existing file's text
 * (or `undefined`/empty-string equivalent if the file doesn't exist yet —
 * a fresh minimal config is synthesised in that case, matching the
 * repo's actual `packages/ui/next.config.ts` shape at the time of writing).
 */
export function generateHeaderFix(
  finding: MissingHeaderFinding,
  currentContent: string | undefined,
): MechanicalFixResult | MechanicalFixSkipped {
  const before = currentContent && currentContent.trim().length > 0 ? currentContent : EMPTY_NEXT_CONFIG;

  if (before.includes("async headers(")) {
    // A headers() function already exists — safely inserting into arbitrary
    // existing logic is exactly the "application logic" case we don't
    // touch. Skip rather than risk a malformed merge.
    return {
      ok: false,
      reason:
        "next.config.ts already defines a headers() function \u2014 auto-merging into existing custom logic " +
        "is out of scope for the mechanical PR generator; needs a human edit.",
    };
  }

  const headerKeyPascal = finding.header
    .split("-")
    .map((s) => s[0].toUpperCase() + s.slice(1))
    .join("-");

  const headersBlock = `  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          { key: "${headerKeyPascal}", value: ${JSON.stringify(finding.recommendedValue)} },
        ],
      },
    ];
  },
`;

  const marker = "const nextConfig: NextConfig = {";
  if (!before.includes(marker)) {
    return {
      ok: false,
      reason: `could not locate "${marker}" in ${finding.configFile} \u2014 file shape is not the expected Next.js config; needs a human edit.`,
    };
  }

  const insertAt = before.indexOf(marker) + marker.length;
  const after = before.slice(0, insertAt) + "\n" + headersBlock + before.slice(insertAt);

  const branchName = `lyrie-auto-fix/add-${finding.header}-header`;
  const prTitle = `fix(security): add missing ${headerKeyPascal} header`;
  const prBody = [
    "## Lyrie auto-remediation \u2014 mechanical fix",
    "",
    `Lyrie's continuous exposure monitor detected that \`${headerKeyPascal}\` is not being sent on responses.`,
    "",
    `**Fix:** add \`${headerKeyPascal}: ${finding.recommendedValue}\` via Next.js's \`headers()\` config hook in \`${finding.configFile}\`.`,
    "",
    "This is a mechanical, config-only change (confidence: high) \u2014 no application logic was touched.",
    "Please verify the header value fits your app's actual CSP/embedding requirements before merging.",
    "",
    "\u2014 generated by Lyrie's auto-remediation PR generator (packages/core/src/remediation-pr/)",
  ].join("\n");

  return {
    ok: true,
    diff: {
      file: finding.configFile,
      newContent: after,
      before,
      after,
      prTitle,
      prBody,
      branchName,
    } satisfies GeneratedDiff,
  };
}
