/**
 * Pure helpers used by the lyrie-action runner — kept separate so they're
 * testable without spawning a full GitHub Actions environment.
 *
 * © OTT Cybersecurity LLC — https://lyrie.ai
 */

export interface Finding {
  id: string;
  title: string;
  severity: "info" | "low" | "medium" | "high" | "critical";
  description: string;
  file?: string;
  line?: number;
  cwe?: string;
  remediation?: string;
}

export interface AttackSurfaceSummary {
  filesInspected: number;
  entryPoints: number;
  trustBoundaries: number;
  dataFlows: number;
  dependencies: number;
  topHotspots: Array<{ file: string; score: number; reasons: string[] }>;
}

export interface ScanResult {
  scanMode: string;
  target: string;
  startedAt: string;
  finishedAt: string;
  findings: Finding[];
  shielded: number;
  /** Lyrie /understand attack-surface map (Phase-2 runner extension). */
  attackSurface?: AttackSurfaceSummary | unknown;
}

export const SEVERITY_RANK: Record<string, number> = {
  none: -1,
  info: 0,
  low: 1,
  medium: 2,
  high: 3,
  critical: 4,
};

export function countBySeverity(findings: Finding[]) {
  const c = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
  for (const f of findings) c[f.severity] = (c[f.severity] ?? 0) + 1;
  return c;
}

function badge(sev: string): string {
  switch (sev) {
    case "critical": return "🟥 **CRITICAL**";
    case "high":     return "🟧 **HIGH**";
    case "medium":   return "🟨 **MEDIUM**";
    case "low":      return "🟩 **LOW**";
    default:         return "⬜ **INFO**";
  }
}

export function renderMarkdown(r: ScanResult): string {
  const counts = countBySeverity(r.findings);
  const lines: string[] = [
    "# 🛡️ Lyrie Pentest Report",
    "",
    `- **Mode:** \`${r.scanMode}\``,
    `- **Target:** \`${r.target}\``,
    `- **Started:** ${r.startedAt}`,
    `- **Finished:** ${r.finishedAt}`,
    `- **Findings:** ${r.findings.length}` +
      ` (critical ${counts.critical}, high ${counts.high}, medium ${counts.medium}, low ${counts.low})`,
    "",
  ];

  if (r.attackSurface && typeof r.attackSurface === "object") {
    const a = r.attackSurface as any;
    if (typeof a.entryPoints === "number" || Array.isArray(a.entryPoints)) {
      const n = Array.isArray(a.entryPoints) ? a.entryPoints.length : a.entryPoints;
      const b = Array.isArray(a.trustBoundaries) ? a.trustBoundaries.length : a.trustBoundaries;
      const f = Array.isArray(a.dataFlows) ? a.dataFlows.length : a.dataFlows;
      const d = Array.isArray(a.dependencies) ? a.dependencies.length : a.dependencies;
      const inspected = a.filesInspected ?? 0;
      lines.push("## 🔍 Attack-surface summary");
      lines.push("");
      lines.push(`- **Files inspected:** ${inspected}`);
      lines.push(`- **Entry points:** ${n}`);
      lines.push(`- **Trust boundaries:** ${b}`);
      lines.push(`- **Tainted data flows:** ${f}`);
      lines.push(`- **Dependencies catalogued:** ${d}`);
      const hotspots = (a.hotspots ?? a.topHotspots ?? []).slice(0, 5);
      if (hotspots.length > 0) {
        lines.push("- **Top hotspots:**");
        for (const h of hotspots) {
          lines.push(`  - \`${h.file}\` (score ${h.score})`);
        }
      }
      lines.push("");
    }
  }

  if (r.findings.length === 0) {
    lines.push("✅ **No findings — Lyrie Shield gave this clean bill of health.**");
    lines.push("");
  } else {
    for (const f of r.findings) {
      lines.push(`## ${badge(f.severity)} ${f.title}`);
      lines.push("");
      if (f.file) lines.push(`- **File:** \`${f.file}\`${f.line ? `:${f.line}` : ""}`);
      if (f.cwe) lines.push(`- **CWE:** ${f.cwe}`);
      lines.push("");
      lines.push(f.description);
      if (f.remediation) {
        lines.push("");
        lines.push(`**Remediation:** ${f.remediation}`);
      }
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("Generated by [Lyrie Agent](https://lyrie.ai) · Lyrie.ai by **OTT Cybersecurity LLC** · MIT-licensed.");
  return lines.join("\n");
}

// SARIF 2.1.0 surface (subset Lyrie emits)
// Spec reference: https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html

export type SarifLevel = "none" | "note" | "warning" | "error";

export interface SarifMultiformatMessageString {
  text: string;
  markdown?: string;
}

export interface SarifReportingDescriptor {
  id: string;
  name: string;
  shortDescription: SarifMultiformatMessageString;
  fullDescription?: SarifMultiformatMessageString;
  help?: SarifMultiformatMessageString;
  helpUri: string;
  defaultConfiguration?: { level: SarifLevel; rank?: number };
  properties?: {
    /** Tags surface in the GitHub Code Scanning UI (e.g. "security", "cwe-79"). */
    tags?: string[];
    /** Floating 0–10; GitHub uses this for the security-severity sidebar. */
    "security-severity"?: string;
    /** Lyrie-extension fields. */
    "lyrie:category"?: string;
    "lyrie:cwe"?: string;
    "lyrie:source"?: "shield" | "mapper" | "scanner" | "validator" | "intel" | "proxy";
  };
  relationships?: Array<{
    target: { id: string; toolComponent?: { name: string } };
    kinds: string[];
  }>;
}

export interface SarifResult {
  ruleId: string;
  level: SarifLevel;
  message: SarifMultiformatMessageString;
  locations?: Array<{
    physicalLocation: {
      artifactLocation: { uri: string };
      region?: { startLine: number; startColumn?: number; endLine?: number; endColumn?: number };
    };
  }>;
  /** Lyrie-grade dedup hashes — GitHub uses these to merge duplicate alerts across runs. */
  partialFingerprints?: Record<string, string>;
  properties?: {
    "security-severity"?: string;
    "lyrie:confidence"?: string;
    "lyrie:category"?: string;
    "lyrie:cwe"?: string;
  };
}

export interface SarifLog {
  $schema: string;
  version: "2.1.0";
  runs: Array<{
    tool: {
      driver: {
        name: string;
        informationUri: string;
        version: string;
        organization?: string;
        semanticVersion?: string;
        rules: SarifReportingDescriptor[];
      };
    };
    properties?: {
      lyrieRunId?: string;
      generatedBy?: string;
    };
    results: SarifResult[];
  }>;
}

// ─── Severity → SARIF mapping ───────────────────────────────────────────────

function sarifLevelFor(severity: Finding["severity"]): SarifLevel {
  if (severity === "critical" || severity === "high") return "error";
  if (severity === "medium") return "warning";
  if (severity === "low" || severity === "info") return "note";
  return "note";
}

/** GitHub Code Scanning uses 0–10 "security-severity" to drive its UI. */
function securitySeverityFor(severity: Finding["severity"]): string {
  switch (severity) {
    case "critical": return "9.5";
    case "high":     return "8.0";
    case "medium":   return "5.5";
    case "low":      return "3.0";
    case "info":     return "1.0";
    default:         return "3.0";
  }
}

/** Heuristic source classifier so each rule advertises which Lyrie module produced it. */
function sourceFor(f: Finding): NonNullable<SarifReportingDescriptor["properties"]>["lyrie:source"] {
  const id = f.id.toLowerCase();
  if (id.startsWith("lyrie-shield")) return "shield";
  if (id.startsWith("lyrie-flow")) return "mapper";
  if (id.startsWith("lyrie-jsts") || id.startsWith("lyrie-py") || id.startsWith("lyrie-go") ||
      id.startsWith("lyrie-php") || id.startsWith("lyrie-rb") || id.startsWith("lyrie-cpp")) {
    return "scanner";
  }
  if (f.description?.includes("Lyrie Threat-Intel")) return "intel";
  if (id.includes("proxy")) return "proxy";
  return "validator";
}

function tagsFor(f: Finding, source: string): string[] {
  const tags = ["security", `lyrie:${source}`];
  if (f.cwe) tags.push(f.cwe.toLowerCase().replace(/[^a-z0-9-]/g, "-"));
  return tags;
}

/** Lightweight stable fingerprint so GitHub dedupes alerts across runs. */
function fingerprintFor(f: Finding): string {
  // We avoid running an actual hash here to keep the helpers dependency-free;
  // the (file, line, ruleFamily) tuple is stable across PR pushes which is
  // what GitHub Code Scanning needs for alert continuity.
  const ruleFamily = f.id.replace(/-\d+$/, "").replace(/-[A-Za-z0-9_/.\-]+:\d+$/, "");
  return `${ruleFamily}|${f.file ?? "-"}|${f.line ?? 0}`;
}

function extractRule(f: Finding): SarifReportingDescriptor {
  const source = sourceFor(f) ?? "validator";
  const cwe = f.cwe ?? "";
  return {
    id: f.id,
    name: f.title,
    shortDescription: { text: f.title },
    fullDescription: f.description
      ? { text: f.description.split("\n")[0] ?? f.description }
      : undefined,
    help: f.remediation
      ? {
          text: f.remediation,
          markdown: `**Remediation:** ${f.remediation}\n\n_Surfaced by Lyrie Agent (\`${source}\`) — Lyrie.ai by **OTT Cybersecurity LLC**._`,
        }
      : {
          text: `Lyrie surfaced this via the \`${source}\` module. See the report for full context.`,
          markdown: `Lyrie surfaced this via the \`${source}\` module. _Lyrie.ai by **OTT Cybersecurity LLC**._`,
        },
    helpUri: `https://lyrie.ai/docs/findings/${encodeURIComponent(f.id)}`,
    defaultConfiguration: { level: sarifLevelFor(f.severity) },
    properties: {
      tags: tagsFor(f, source),
      "security-severity": securitySeverityFor(f.severity),
      "lyrie:source": source,
      "lyrie:cwe": cwe || undefined,
    },
    relationships: cwe
      ? [{ target: { id: cwe, toolComponent: { name: "CWE" } }, kinds: ["superset"] }]
      : undefined,
  };
}

export function renderSarif(r: ScanResult): SarifLog {
  const rules = new Map<string, SarifReportingDescriptor>();
  const results: SarifResult[] = [];

  for (const f of r.findings) {
    if (!rules.has(f.id)) rules.set(f.id, extractRule(f));
    const source = sourceFor(f) ?? "validator";
    const cwe = f.cwe ?? "";

    // Pull "Lyrie Stages A–F: ... confidence NN%" out of description, if present.
    const confMatch = (f.description ?? "").match(/confidence\s+(\d+)%/i);
    const confidence = confMatch ? `${confMatch[1]}%` : undefined;

    results.push({
      ruleId: f.id,
      level: sarifLevelFor(f.severity),
      message: {
        text: f.description,
        markdown:
          f.description.replace(/\n/g, "\n\n") +
          "\n\n_Surfaced by Lyrie.ai by **OTT Cybersecurity LLC**._",
      },
      locations: f.file
        ? [{
            physicalLocation: {
              artifactLocation: { uri: f.file },
              region: f.line ? { startLine: f.line } : undefined,
            },
          }]
        : undefined,
      partialFingerprints: { lyrieFingerprint: fingerprintFor(f) },
      properties: {
        "security-severity": securitySeverityFor(f.severity),
        "lyrie:source": source,
        "lyrie:confidence": confidence,
        "lyrie:cwe": cwe || undefined,
      },
    });
  }

  return {
    $schema: "https://json.schemastore.org/sarif-2.1.0.json",
    version: "2.1.0",
    runs: [{
      tool: {
        driver: {
          name: "Lyrie Pentest",
          organization: "OTT Cybersecurity LLC",
          informationUri: "https://lyrie.ai",
          version: "0.2.6",
          semanticVersion: "0.2.6",
          rules: Array.from(rules.values()),
        },
      },
      properties: {
        generatedBy: "Lyrie.ai by OTT Cybersecurity LLC",
      },
      results,
    }],
  };
}
